### ISSUE TITLE
requires peer dependency

### ISSUE THREAD

**Issue by lucidtheory** [nikolaiwarner/react-native-text-input-reset#2]
`npm WARN react-native-text-input-reset@1.0.1 requires a peer of react-native@^0.41.2 but none was installed.`

I get this error when running npm install. I am running an expo app on version 21 using react native .48 though so I'm not sure where this is coming from or how to fix. Help?

Dependencies: 

```
  "dependencies": {
    "axios": "^0.16.2",
    "expo": "^21.0.0",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",
    "react-native-actioncable": "0.0.3",
    "react-native-animatable": "^1.2.3",
    "react-native-datepicker": "^1.5.1",
    "react-native-elements": "git://github.com/react-native-training/react-native-elements.git#next",
    "react-native-geocoding": "^0.2.0",
    "react-native-google-shortener": "^1.1.0",
    "react-native-hyperlink": "0.0.10",
    "react-native-image-to-base64": "^0.1.0",
    "react-native-keyboard-aware-scroll-view": "^0.3.0",
    "react-native-modal-dropdown": "^0.5.0",
    "react-native-popup-menu": "^0.7.5",
    "react-native-text-input-reset": "^1.0.1",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.6.0",
    "redux-persist": "^4.8.0",
    "redux-thunk": "^2.2.0",
    "sentry-expo": "~1.6.0"
  },
```

**Comment by lucidtheory** [comment]
I got it up but for some reason the module is coming in undifined when I import it? `{default: undefined}` is what prints out when I console.log the module after importing and I get an unhandled promise rejection when I call ` TextInputReset.resetKeyboardInput(findNodeHandle(this.textInput))` because TextInputReset is undefined but I do import it as per the Readme

**Comment by sibelius** [comment]
can we just remove peer dep?
